services:
  - type: web
    name: insurance-agent-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASS
        sync: false
      - key: WA_TOKEN
        sync: false
      - key: WA_PHONE_ID
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_KEY
        sync: false
      - key: CLOUD_SECRET
        sync: false

